### ISSUE TITLE
maven central

### ISSUE THREAD

**Issue by LucianoZu** [Ardulink/Ardulink#16]
We should setup poms to deploy our artifacts on a maven repo. I start to setup they but actually there are still some problems.

**Comment by pfichtner** [comment]
All the needed information must be placed in the existing poms, no need to create new ones. 
Do you want to publish Ardulink-1 on maven central? What's about Ardulink-2? I think we should move or duplicate this issue to Ardulink-2.

**Comment by LucianoZu** [comment]
Oh, yes of course is for Ardulink-2.
