### ISSUE TITLE
Gereralize ArdulinkMail xml configuration and insert in into utility

### ISSUE THREAD

**Issue by LucianoZu** [Ardulink/Ardulink#9]

**Comment by pfichtner** [comment]
To make an xml tree of an object an vice versa I'd propose the usage of XStream (no JAXB annotations at all needed and will work with all objects). 

So loading/saving will become one liners: 

```
AConfiguration loaded = ConfigurationFacade.loadConfiguration();
String xml = xStream.toXML(loaded);
System.out.println(xml);
AConfiguration fromXML = (AConfiguration) xStream.fromXML(xml);
System.out.println(fromXML);
```

There is no need to introduce such things like trying to find he right constructor: XStream does handle this all internally. Consider XStream as XML serialization. 
Also the following will work: 

```
SerialConnection loaded = new SerialConnection("42");
String xml = xStream.toXML(loaded);
System.out.println(xml);
SerialConnection fromXML = (SerialConnection) xStream.fromXML(xml);
System.out.println(fromXML);
```

XStream is available at maven central

```
<dependency>
    <groupId>com.thoughtworks.xstream</groupId>
    <artifactId>xstream</artifactId>
    <version>1.4.8</version>
</dependency>
```

**Comment by LucianoZu** [comment]
When I though to Ardulink the first time. I though to minimize external dependencies because java beginner programmers could add just few jars in their project. And a maker often is a java beginner. So I'd like to add just external libs that add very good features (for instance slf4j you have introduced). I have to read something about XStream that I don't know. It seems interesting the XStream feature that serialize a class without need for a specific model.

**Comment by LucianoZu** [comment]
out of date...
